// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8wZboJ332k9SRb2amvFS47-t7CFw0_Qw',
    appId: '1:808231147377:web:f4182ad2bc368989f608d0',
    messagingSenderId: '808231147377',
    projectId: 'mrfreddy-2a033',
    authDomain: 'mrfreddy-2a033.firebaseapp.com',
    storageBucket: 'mrfreddy-2a033.appspot.com',
    measurementId: 'G-JDS8VCNT1L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDW0Ss4d8FL7end3xBbYj0Qh_H4XsDxhHo',
    appId: '1:808231147377:android:d4ba13aac6adbb16f608d0',
    messagingSenderId: '808231147377',
    projectId: 'mrfreddy-2a033',
    storageBucket: 'mrfreddy-2a033.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYBRDRQhYPPQeFaaoC02OURyxlKcjoDZY',
    appId: '1:808231147377:ios:002e74dc64a93beaf608d0',
    messagingSenderId: '808231147377',
    projectId: 'mrfreddy-2a033',
    storageBucket: 'mrfreddy-2a033.appspot.com',
    iosBundleId: 'com.example.mrfreddy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYBRDRQhYPPQeFaaoC02OURyxlKcjoDZY',
    appId: '1:808231147377:ios:05a15e5780d4ea08f608d0',
    messagingSenderId: '808231147377',
    projectId: 'mrfreddy-2a033',
    storageBucket: 'mrfreddy-2a033.appspot.com',
    iosBundleId: 'com.example.mrfreddy.RunnerTests',
  );
}
